apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "kubecrsh.fullname" . }}-test-connection"
  namespace: {{ include "kubecrsh.namespace" . }}
  labels:
    {{- include "kubecrsh.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  containers:
    - name: wget
      image: busybox:1.36
      command: ['wget']
      args: ['{{ include "kubecrsh.fullname" . }}:{{ .Values.service.port }}/health', '-O', '-']
  restartPolicy: Never
