apiVersion: v1
kind: ConfigMap
metadata:
  name: kubecrsh-config
  namespace: kubecrsh
data:
  config.yaml: |
    namespace: kubecrsh
    reports:
      path: /data/reports
      retention: 168h
    watch:
      reasons:
        - OOMKilled
        - Error
        - CrashLoopBackOff
